import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { saveAs } from 'file-saver';
import type { Note } from '../services/note.service';

export const exportUtils = {
  /**
   * Generates and downloads a beautifully formatted PDF document.
   */
  downloadPDF: async (note: Note) => {
    // Create new PDF document
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const extendedNote = note as any;
    
    // Formatting constants
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    let yPos = margin;
    
    // Helpers
    const checkPageBreak = (neededHeight: number) => {
      if (yPos + neededHeight > pageHeight - margin) {
        doc.addPage();
        yPos = margin;
      }
    };
    
    const addFooter = () => {
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Generated by LearnFlow AI - ${new Date().toLocaleString()}`, margin, pageHeight - 10);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, pageHeight - 10);
      }
    };

    // Title
    doc.setFontSize(24);
    doc.setTextColor(40, 40, 40);
    const title = note.title || note.originalFileName || 'LearnFlow AI Note';
    doc.text(title, margin, yPos, { maxWidth: pageWidth - margin * 2 });
    yPos += 15;

    // Summary
    if (note.summary) {
      checkPageBreak(30);
      doc.setFontSize(16);
      doc.setTextColor(60, 60, 60);
      doc.text('Summary', margin, yPos);
      yPos += 8;
      
      doc.setFontSize(11);
      doc.setTextColor(80, 80, 80);
      const splitSummary = doc.splitTextToSize(note.summary, pageWidth - margin * 2);
      doc.text(splitSummary, margin, yPos);
      yPos += splitSummary.length * 6 + 10;
    }

    // Key Points
    if (note.keyPoints && note.keyPoints.length > 0) {
      checkPageBreak(40);
      doc.setFontSize(16);
      doc.setTextColor(60, 60, 60);
      doc.text('Key Points', margin, yPos);
      yPos += 8;
      
      doc.setFontSize(11);
      doc.setTextColor(80, 80, 80);
      note.keyPoints.forEach(point => {
        const splitPoint = doc.splitTextToSize(`• ${point}`, pageWidth - margin * 2 - 5);
        checkPageBreak(splitPoint.length * 6 + 5);
        doc.text(splitPoint, margin + 5, yPos);
        yPos += splitPoint.length * 6 + 2;
      });
      yPos += 10;
    }

    // Generated Notes (Main body)
    if (note.generatedNotes) {
      checkPageBreak(30);
      doc.setFontSize(16);
      doc.setTextColor(60, 60, 60);
      doc.text('Generated Notes', margin, yPos);
      yPos += 8;
      
      doc.setFontSize(11);
      doc.setTextColor(80, 80, 80);
      
      const paragraphs = note.generatedNotes.split('\n').filter(p => p.trim() !== '');
      paragraphs.forEach(p => {
        const splitP = doc.splitTextToSize(p, pageWidth - margin * 2);
        checkPageBreak(splitP.length * 6 + 5);
        doc.text(splitP, margin, yPos);
        yPos += splitP.length * 6 + 4;
      });
      yPos += 10;
    }

    // Flashcards (If present)
    if (extendedNote.flashcards && extendedNote.flashcards.length > 0) {
      checkPageBreak(40);
      doc.setFontSize(16);
      doc.setTextColor(60, 60, 60);
      doc.text('Flashcards', margin, yPos);
      yPos += 8;

      const tableData = extendedNote.flashcards.map((fc: any) => [fc.question, fc.answer]);
      
      autoTable(doc, {
        startY: yPos,
        head: [['Question', 'Answer']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [124, 58, 237] }, // Brand primary color
        margin: { left: margin, right: margin },
      });
      
      yPos = (doc as any).lastAutoTable.finalY + 15;
    }

    // Add footer to all pages and save
    addFooter();
    doc.save(`${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
  },

  /**
   * Generates and downloads a DOCX (Microsoft Word) document.
   */
  downloadDOCX: async (note: Note) => {
    const extendedNote = note as any;
    const title = note.title || note.originalFileName || 'LearnFlow AI Note';
    const children: any[] = [];

    // Title
    children.push(
      new Paragraph({
        text: title,
        heading: HeadingLevel.HEADING_1,
        spacing: { after: 400 },
      })
    );

    // Summary
    if (note.summary) {
      children.push(
        new Paragraph({ text: 'Summary', heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 200 } }),
        new Paragraph({ text: note.summary, spacing: { after: 200 } })
      );
    }

    // Key Points
    if (note.keyPoints && note.keyPoints.length > 0) {
      children.push(
        new Paragraph({ text: 'Key Points', heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 200 } })
      );
      note.keyPoints.forEach(point => {
        children.push(new Paragraph({ text: point, bullet: { level: 0 } }));
      });
    }

    // Generated Notes
    if (note.generatedNotes) {
      children.push(
        new Paragraph({ text: 'Generated Notes', heading: HeadingLevel.HEADING_2, spacing: { before: 400, after: 200 } })
      );
      const paragraphs = note.generatedNotes.split('\n').filter(p => p.trim() !== '');
      paragraphs.forEach(p => {
        children.push(new Paragraph({ text: p, spacing: { after: 200 } }));
      });
    }

    // Flashcards
    if (extendedNote.flashcards && extendedNote.flashcards.length > 0) {
      children.push(
        new Paragraph({ text: 'Flashcards', heading: HeadingLevel.HEADING_2, spacing: { before: 400, after: 200 } })
      );
      extendedNote.flashcards.forEach((fc: any) => {
        children.push(
          new Paragraph({ children: [new TextRun({ text: 'Q: ', bold: true }), new TextRun(fc.question)] }),
          new Paragraph({ children: [new TextRun({ text: 'A: ', bold: true }), new TextRun(fc.answer)], spacing: { after: 200 } })
        );
      });
    }

    const doc = new Document({
      sections: [{ properties: {}, children }],
      creator: 'LearnFlow AI',
      title: title,
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.docx`);
  },

  /**
   * Generates and downloads a Markdown (.md) file.
   */
  downloadMarkdown: (note: Note) => {
    const extendedNote = note as any;
    let md = '';
    const title = note.title || note.originalFileName || 'LearnFlow AI Note';
    
    md += `# ${title}\n\n`;

    if (note.summary) {
      md += `## Summary\n${note.summary}\n\n`;
    }

    if (note.keyPoints && note.keyPoints.length > 0) {
      md += `## Key Points\n`;
      note.keyPoints.forEach(point => md += `- ${point}\n`);
      md += '\n';
    }

    if (note.generatedNotes) {
      md += `## Generated Notes\n${note.generatedNotes}\n\n`;
    }

    if (extendedNote.flashcards && extendedNote.flashcards.length > 0) {
      md += `## Flashcards\n`;
      extendedNote.flashcards.forEach((fc: any) => {
        md += `**Q:** ${fc.question}\n**A:** ${fc.answer}\n\n`;
      });
    }

    // Add footer
    md += `---\n*Generated by LearnFlow AI on ${new Date().toLocaleString()}*\n`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    saveAs(blob, `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`);
  },

  /**
   * Copies the note's text content to the clipboard.
   */
  copyToClipboard: async (note: Note) => {
    let text = `${note.title || note.originalFileName}\n\n`;
    
    if (note.summary) text += `SUMMARY\n${note.summary}\n\n`;
    
    if (note.keyPoints && note.keyPoints.length > 0) {
      text += `KEY POINTS\n`;
      note.keyPoints.forEach(point => text += `• ${point}\n`);
      text += '\n';
    }
    
    if (note.generatedNotes) text += `GENERATED NOTES\n${note.generatedNotes}\n\n`;

    await navigator.clipboard.writeText(text.trim());
  },

  /**
   * Triggers the browser print dialog.
   */
  printNotes: () => {
    window.print();
  }
};
